apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-image-renderer-envs
  labels:
    app: grafana-image-renderer-envs
data: 
  environments: |
  GF_RENDERING_SERVER_URL: http://renderer:8081/render
  GF_RENDERING_CALLBACK_URL: http://grafana:3000/
  GF_LOG_FILTERS: rendering:debug